import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Header from "./components/Header";
import { api } from "~/utils/api";
import Main from "./components/Main";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post It</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
    </>
  );
};

export default Home;
